### ISSUE TITLE
parent_id should be optional

### ISSUE THREAD

**Issue by andrewlock** [DataDog/dd-apm-test-agent#65]
Hey, I was just giving this a try with [the .NET Tracer](https://github.com/DataDog/dd-trace-dotnet), but I'm currently getting an error when we try and send traces, as we don't send the parent id if it's null:

```
INFO:ddapm_test_agent.agent:received trace payload with 1 trace chunks
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/agent.py", line 68, in check_failure_middleware
    response = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/agent.py", line 100, in session_token_middleware
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/agent.py", line 202, in handle_v04_traces
    return await self._handle_traces(request, version="v0.4")
  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/agent.py", line 241, in _handle_traces
    pprint_trace(trace, request.app["log_span_fmt"]),
  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/trace.py", line 197, in pprint_trace
    cmap = child_map(trace)
  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/trace.py", line 143, in child_map
    cmap[s["parent_id"]] = []
KeyError: 'parent_id'
INFO:aiohttp.access:172.27.0.3 [25/Apr/2022:13:59:10 +0000] "POST /v0.4/traces HTTP/1.1" 500 244 "-" "-"
```

I can see from the comments there's discussion about whether it should be `Optional` or not, so I think yes, yes it should 😄 

https://github.com/DataDog/dd-apm-test-agent/blob/master/ddapm_test_agent/trace.py#L55

**Comment by brettlangdon** [comment]
Yes, this could be optional since in Go when we unpack if it isn't there you get the data type default... which would be `0` in this case, which is the valid "no parent id" value

**Comment by Kyle-Verhoog** [comment]
that resolves that `TODO` 😄

**Comment by andrewlock** [comment]
Thanks for fixing @Kyle-Verhoog and @brettlangdon! Was just trying it out again, and this fixes the issue for sending traces, but there is still a `parent_id` issue in the snapshot part. Hopefully the logs below will make for an easy fix? 🙂 

```
INFO:ddapm_test_agent.agent:performing snapshot with token='LOCALTEST', ci_mode=0 and snapshot directory='/snapshots'

INFO:ddapm_test_agent.agent:using ignores ['span_id', 'parent_id', 'metrics.system.pid', 'meta.runtime-id', 'trace_id', 'duration', 'start']

INFO:ddapm_test_agent.agent:using snapshot files 'smoke_test_snapshots.json' and 'smoke_test_snapshots_tracestats.json'

ERROR:aiohttp.server:Error handling request

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request

    resp = await request_handler(request)

  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle

    resp = await handler(request)

  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl

    return await handler(request)

  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/agent.py", line 68, in check_failure_middleware

    response = await handler(request)

  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/agent.py", line 100, in session_token_middleware

    return await handler(request)

  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/agent.py", line 341, in handle_snapshot

    f.write(trace_snapshot.generate_snapshot(received_traces))

  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/trace_snapshot.py", line 350, in generate_snapshot

    return _snapshot_json(_normalize_traces(received_traces))

  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/trace_snapshot.py", line 114, in _normalize_traces

    normed_traces.append(_normalize_trace(trace, i))

  File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/trace_snapshot.py", line 97, in _normalize_trace

    if span["parent_id"]:

KeyError: 'parent_id'
```
